---
- hosts: all
  sudo: yes
  tasks:
    - name: Create the ec2-user
      user: name=ec2-user comment="The ec2 user" group=wheel
    - lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'

    - name: Set fake ip address
      set_fact:
        ansible_ec2_local_ipv4: "{{ ansible_eth0.ipv4.address }}"
        docker_api_version: '1.3.2'
    - name: yum install packages
      yum: pkg={{ item }} state=present enablerepo=epel
      with_items:
        - openssh-clients
        - python-crypto
        - python-crypto2.6
        - python-devel
    - name: setup ansible
      pip: name="{{ item }}" state=present
      with_items:
        - 'boto>=2.32.1'
        - 'ansible>=1.8,<1.9'

- include: ansible-balanced-stalk-docker/bootstrap.yml